name: Force GitHub Pages Deployment

on:
  # ✅ 每天定时运行一次（UTC 0 点，即北京时间早上 8 点）
  schedule:
    - cron: '0 0 * * *'

  # ✅ 监听 gh-pages 分支更新时也触发
  push:
    branches: ['gh-pages']

  # ✅ 手动触发（可选）
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create empty commit to trigger GitHub Pages deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Trigger GitHub Pages deploy"
          git push https://github.com/GalahadL06/galahadl06.github.io.git gh-pages
